site_name: HÃ¤lsa Hemma QMS
site_description: Operational QMS documentation
theme:
  name: material
nav:
  - Home: index.md
  - Checklists:
      - 1A Platform Change (Non-MDR): checklists/1A-platform-change-non-mdr.md
      - 2A Technical File (Non-MDR): checklists/2A-technical-file-non-mdr.md
  - Loops:
      - Post-release surveillance: loops/surveillance.md
      - Incidents & deviations: loops/incidents.md
      - Management review: loops/management-review.md
      - Training: loops/training.md
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - toc:
      permalink: true